stages:
  - build
  - test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: build
  image: composer:latest
  script:
    - composer install --ignore-platform-reqs
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/

phpunit:
  stage: test
  image: php:latest
  variables:
    MYSQL_DATABASE: acadelib_testing
    MYSQL_ROOT_PASSWORD: secret
  services:
    - name: mariadb:latest
      alias: mariadb
  dependencies:
    - composer
  before_script:
    - apt-get update -yqq
    - docker-php-ext-install pdo_mysql
  script:
    - cp .env.gitlabci .env
    - php artisan key:generate
    - vendor/bin/phpunit
